apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml
  #- https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
  #- cert-manager.yaml
  - ingress-nginx.yaml
  - weave-gitops.yaml
patches:
  - target:
      kind: Deployment
      name: "metrics-server"
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls

