apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.19.0.100/32


---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-announcement
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool

